apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "presto.worker" . }}
  labels:
    app: presto
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: worker
spec:
  replicas: {{ .Values.worker.count }}
  selector:
    matchLabels:
      app: presto
      release: {{ .Release.Name }}
      component: worker
  template:
    metadata:
      labels:
        app: presto
        release: {{ .Release.Name }}
        component: worker
    spec:
      securityContext:
        runAsUser: 186
        runAsGroup: 186
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "presto.worker" . }}
        - name: catalog-volume
          configMap:
            name: {{ template "presto.catalog" . }}
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /opt/presto/etc
              name: config-volume
            - mountPath: /opt/presto/etc/catalog
              name: catalog-volume
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/info
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /v1/info
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      terminationGracePeriodSeconds: 1200
