apiVersion: v1
kind: Service
metadata:
  name: {{ template "presto.service.name" . }}
  labels:
    app: presto
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: presto
    release: {{ .Release.Name }}
    component: coordinator
